package lp2.projeto;

public enum Preferencias {
	DETESTO,
	ACHO_MUITO_RUIM,
	ACHO_BASTANTE_RUIM,
	ACHO_RUIM, 
	ACHO_UM_POUCO_RUIM, 
	NAO_E_RUIM, 
	E_BONZINHO, 
	BASTANTE_BOM, 
	MUITO_BOM, 
	INCRIVEL_SENSASIONAL_IMPRESSIONANTE;
}
